export const SUPABASE_CONSTANTS = {
  TABLES: {
    ACCOUNTS: {
      _: 'accounts',
      ID: 'id',
      NAME: 'name',
      BALANCE: 'balance',
      USER_ID: 'user_id',
      CREATED_AT: 'created_at',
      UPDATED_AT: 'updated_at',
    },
    CATEGORIES: {
      _: 'categories',
      ID: 'id',
      NAME: 'name',
      CREATED_AT: 'created_at',
      USER_ID: 'user_id',
      UPDATED_AT: 'updated_at',
    },
    EXPENSES: {
      _: 'expenses',
      ID: 'id',
      NAME: 'name',
      AMOUNT: 'amount',
      CATEGORY: 'category',
      FROM_ACCOUNT: 'from_account',
      USER_ID: 'user_id',
      CREATED_AT: 'created_at',
      UPDATED_AT: 'updated_at',
    },
    INCOMES: {
      _: 'incomes',
      ID: 'id',
      NAME: 'name',
      AMOUNT: 'amount',
      TO_ACCOUNT: 'to_account',
      CATEGORY: 'category',
      USER_ID: 'user_id',
      CREATED_AT: 'created_at',
      UPDATED_AT: 'updated_at',
    },
    TRANSACTIONS: {
      _: 'transactions',
      ID: 'id',
      CREATED_AT: 'created_at',
      NAME: 'name',
      FROM_ACCOUNT: 'from_account',
      TO_ACCOUNT: 'to_account',
      AMOUNT: 'amount',
      USER_ID: 'user_id',
      UPDATED_AT: 'updated_at',
    },
  },
  ENV: {
    PROJECT_KEY: 'VITE_SUPABASE_PROJECT_KEY',
    PROJECT_URL: 'VITE_SUPABASE_PROJECT_URL',
    ANON_KEY: 'VITE_SUPABASE_ANON_KEY',
  },
} as const;
